name: CI

on:
  push:
    branches: [ main, feat/**, fix/**, chore/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_SUPABASE_URL: "https://example.supabase.co"
      EXPO_PUBLIC_SUPABASE_ANON_KEY: "anon_key_placeholder"
      CI: "true"
      EXPO_NO_DOTENV: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build web (Expo export)
        run: npm run build:web

      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist


